### ISSUE TITLE
Browser proxy option doesn't seem to work

### ISSUE THREAD

**Issue by tercerojista** [rodolpheche/wiremock-docker#1]
I'm trying to use this container with the `-e WIREMOCK_ARGS="--enable-browser-proxy"` flag. Wiremock starts and reports that it does have browser proxying enabled. But the forward proxy doesn't seem to work when wiremock is containerised.

I can get the proxying to work when I use the standalone, but not using this container. Any idea what the issue might be?

**Comment by rodolpheche** [comment]
Did you publish the container's port 8080 to the host with -p argument ?

**Comment by tercerojista** [comment]
I think that must've been the issue... Yes, it works fine when I configure things correctly!
