### ISSUE TITLE
Passing arguments to docker run breaks $JAVA_OPTS

### ISSUE THREAD

**Issue by symposion** [rodolpheche/wiremock-docker#17]
The entry point script does not include $JAVA_OPTS in it, so if you pass arguments to docker run (overriding the CMD in the Dockerfile), $JAVA_OPTS is silently ignored. I think it should be included in the "backup" command in docker-entrypoint.sh as well to prevent this.

**Comment by rodolpheche** [comment]
Thanks for your report
