### ISSUE TITLE
Wrong image pushed to docker hub for latest tag

### ISSUE THREAD

**Issue by symposion** [rodolpheche/wiremock-docker#18]
I was confused by the fact that the "latest" image did not appear to be showing the most recent fixes despite being pushed very recently to docker hub. Looking closely at https://hub.docker.com/r/rodolpheche/wiremock/tags, however, it seems like the size of the latest image matches that of 2.23.0 rather than 2.24.0. Did the wrong image get pushed as latest perhaps?

**Comment by ghusta** [comment]
According to this command 
> docker inspect  --format "{{.Config.Env}}" rodolpheche/wiremock:latest

It contains wiremock **2.23.2**

**Comment by rodolpheche** [comment]
Thanks for your report
