### ISSUE TITLE
Swagger UI is not loading inside the container

### ISSUE THREAD

**Issue by dstarosta** [rodolpheche/wiremock-docker#19]
**Steps to reproduce**

1. Run the container.
`docker run -it --rm -p 8080:8080 rodolpheche/wiremock`

2. Load the Swagger UI in Chrome (or Firefox).
http://pcname:8080/__admin/swagger-ui/

It takes a minute or so to load the page then it stops without loading any content. In the developer console Chrome prints the following error for each of the CSS and JS files.
"Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH"

Firefox print a more generic "load failing" error.

Direct links to content are:

/__admin/swagger-ui/swagger-ui-dist/swagger-ui.css
/__admin/swagger-ui/swagger-ui-dist/swagger-ui-bundle.js

I have tried a few previous versions of the containers and they behave the same way. Running Wiremock of the same version without the container does not have this problem.

**The underlying issue**

Those URLs respond using chunked transfer "Accept-Range: bytes" that does not have the "Content-Length" attribute. A lot of garbage binary data is being added to the actual response.

**Comment by rodolpheche** [comment]
I randomly reproduced the issue you described. I can't explain this behavior.

However, I investigated and I came across this article : https://tech.xing.com/a-reason-for-unexplained-connection-timeouts-on-kubernetes-docker-abd041cf7e02

**Comment by dstarosta** [comment]
Just to follow up on this, installing Linkerd fixed the problem.

**Comment by bcappoen** [comment]
hi @rodolpheche , i have the same issue. Do you have a solution ?
