### ISSUE TITLE
How to enable response templating?

### ISSUE THREAD

**Issue by dandraka** [rodolpheche/wiremock-docker#20]
Hi Rodolphe, thanks for your docker, it's really useful.

One question: when I run wiremock locally (using the jar) I use --global-response-templating. Is there a way to enable that in your image?

Many thanks and regards,

Jim

**Comment by rodolpheche** [comment]
https://github.com/rodolpheche/wiremock-docker#start-a-wiremock-container-with-wiremock-arguments
