### ISSUE TITLE
Windows PowerShell script

### ISSUE THREAD

**Issue by megadix** [rodolpheche/wiremock-docker#23]
Hi,
I use this Wiremock docker image under Windows (PowerShell) but I often need to change parameters of the container: ports, interactive or not, --rm switch, verbose mode.

I created a PowerShell script to automate this:
https://gist.github.com/megadix/98daa4b5fd52fdcb96312f92016e3490

Could you please link it in the documentation? Windows devs also deserve to be happy :)

Thank you,
Dimitri

**Comment by rodolpheche** [comment]
Hi,
This repository only handles the Wiremock Docker image build and deployment, it should remain agnostic to runner tool.
