### ISSUE TITLE
Please, add ability to override port inside Docker containter

### ISSUE THREAD

**Issue by usmanovbf** [rodolpheche/wiremock-docker#24]
Because in some cases I need to solve collision with 8080 port of other Docker instance inside the same network.
It'll be good if something like that:
```  
wiremock:
    image: rodolpheche/wiremock
    environment:
      - PORT=8081
    ports:
      - 8081:8081

**Comment by rodolpheche** [comment]
Please read the doc before opening issue...

https://github.com/rodolpheche/wiremock-docker#start-a-wiremock-container-with-wiremock-arguments
http://wiremock.org/docs/running-standalone/
