### ISSUE TITLE
Is it possible to rewrite context root for path routing?

### ISSUE THREAD

**Issue by peterpakos** [rodolpheche/wiremock-docker#28]
I'm trying to deploy wiremock service in AWS ECS and route /wiremock/* requests to it but all I'm getting is this message, no matter what path I use (even /__admin/):

> No response could be served as there are no stub mappings in this WireMock instance.

Is it possible to rewrite/set context root for the service? I've looked at the documentation but failed to find a way of doing it.

**Comment by rodolpheche** [comment]
This repository only handles the Wiremock Docker image build and deployment, it should remain agnostic to integration considerations.
