### ISSUE TITLE
--verbose parameter causing disk space problems

### ISSUE THREAD

**Issue by szymon-owczarzak** [rodolpheche/wiremock-docker#39]
When using `--verbose` parameter to run `rodolpheche/wiremock` container and if the container runs long enough it will use all available space from the server for creating log files.
We had this problem in app i work on: https://github.com/wttech/cogboard/pull/327/files

Please consider adding a TIP about this to your read.me file and happy new year :)

**Comment by rodolpheche** [comment]
This is not a problem, you must have used the default Docker logging options.

You could limit the space used by the container logging file, you just have to setup the JSON File logging driver options.
This might help you : https://docs.docker.com/config/containers/logging/json-file/
Docker Compose syntax : https://docs.docker.com/compose/compose-file/compose-file-v3/#logging

**Comment by szymon-owczarzak** [comment]
Thanks, I will try that 👍
