### ISSUE TITLE
Dockerfile uses deprecated java image

### ISSUE THREAD

**Issue by a-k-g** [rodolpheche/wiremock-docker#4]
From https://hub.docker.com/_/java/:

> This image is officially deprecated in favor of the openjdk image, and will receive no further updates after 2016-12-31 (Dec 31, 2016). Please adjust your usage accordingly.

It would be great if this could switch to the new image. Also, can this be switched to use the `openjdk:8-jre` (309 MB) or `openjdk:8-jre-alpine` (108 MB)? The `8-jdk` image is much bigger (643 MB) and doesn't seem necessary.

Happy to contribute the changes if you think they seem reasonable!

**Comment by rodolpheche** [comment]
Hi !
I totally agree with you.
The next release will be based on the openjdk JRE instead of Oracle Java JDK.
Thanks for the contribution !

**Comment by a-k-g** [comment]
Thanks for also publishing with the alpine image!
