### ISSUE TITLE
Using docker-compose to start image

### ISSUE THREAD

**Issue by mspeich-sirius** [rodolpheche/wiremock-docker#5]
docker-compose doesn't yet support passing arguments to the entrypoint script. That means that this image can't be launching using docker-compose. Can the arguments be converted to environment variables?

**Comment by rodolpheche** [comment]
docker-compose supports passing arguments to the entrypoint script using **command** keyword.

**Comment by mspeich-sirius** [comment]
Thanks, that helps. I had looked at using command before, but I didn't want to override the command in your dockerfile. Now I see that your entrypoint re-establishes the original command if you override the default one, plus adds the parameters. Here is the compose file I came up with if you want it.
[docker-compose.zip](https://github.com/rodolpheche/wiremock-docker/files/846059/docker-compose.zip)
