### ISSUE TITLE
Expose port 80,443 instead of 8080,8443 and allow docker run command to override if need be

### ISSUE THREAD

**Issue by johnhydemtm365** [rodolpheche/wiremock-docker#8]
Hi, excellent docker image by the way got it up and running quickly, however, I was wondering if its possible to expose ports 80 and 443 instead of 8080 and 8443 and allow the user running the docker image to then specify a mapping if need be.

The reason is I want to run this in an azure container and it does not allow me to change the mapping at all so defaults to 80 and it does not map down....

I know wire mock can be run on different ports than the default, I am not a bash expert so cannot see where to tweak the entry point file..?

Thanks for any assistance :-)

John

**Comment by rodolpheche** [comment]
Hi!

Default exposed ports are 8080 and 8443 because these are the common development ports.

I'me not sure to understand your problem.
If you just want to override docker port binding to expose port 80/443 on the host, use these commands :
```bash
# http
docker run -p 80:8080 rodolpheche/wiremock
#https
docker run -p 443:8443 rodolpheche/wiremock --https-port 8443
```

Rod
