### ISSUE TITLE
Error running 2.16.0 in docker compose

### ISSUE THREAD

**Issue by madstanners** [rodolpheche/wiremock-docker#9]
I'm getting

```
ERROR: readlink /var/lib/docker/overlay2/l: invalid argument
```

When I'm using latest (2.16.0) from docker compose. I reverted to 2.15.0 and this seems to have resolved the issue. 

I'm using Arch Linux and `Docker version 18.03.0-ce, build 0520e24302`

Thanks

**Comment by rodolpheche** [comment]
Could you provide a docker-compose file so that I can reproduce ?
